// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  bossType: __t.string().name("boss_type"),
  hp: __t.u64(),
  maxHp: __t.u64().name("max_hp"),
  posX: __t.i64().name("pos_x"),
  posZ: __t.i64().name("pos_z"),
  phase: __t.u64(),
  isAlive: __t.bool().name("is_alive"),
  isDazed: __t.bool().name("is_dazed"),
  dazedUntil: __t.option(__t.timestamp()).name("dazed_until"),
  isMarked: __t.bool().name("is_marked"),
  markedUntil: __t.option(__t.timestamp()).name("marked_until"),
  spawnedAt: __t.timestamp().name("spawned_at"),
  diedAt: __t.option(__t.timestamp()).name("died_at"),
  ability1CooldownUntil: __t.option(__t.timestamp()).name("ability_1_cooldown_until"),
  ability2CooldownUntil: __t.option(__t.timestamp()).name("ability_2_cooldown_until"),
  isHidden: __t.bool().name("is_hidden"),
  isBurrowed: __t.bool().name("is_burrowed"),
  isChanneling: __t.bool().name("is_channeling"),
  knockedPlayerId: __t.option(__t.u64()).name("knocked_player_id"),
});
