// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  enemyType: __t.string().name("enemy_type"),
  hp: __t.u64(),
  maxHp: __t.u64().name("max_hp"),
  posX: __t.i64().name("pos_x"),
  posZ: __t.i64().name("pos_z"),
  speedMultiplier: __t.u64().name("speed_multiplier"),
  isDazed: __t.bool().name("is_dazed"),
  dazedUntil: __t.option(__t.timestamp()).name("dazed_until"),
  isAlive: __t.bool().name("is_alive"),
  isMarked: __t.bool().name("is_marked"),
  markedUntil: __t.option(__t.timestamp()).name("marked_until"),
  lastSpitAt: __t.option(__t.timestamp()).name("last_spit_at"),
  diedAt: __t.option(__t.timestamp()).name("died_at"),
  spawnedAt: __t.option(__t.timestamp()).name("spawned_at"),
});
