// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  lobbyId: __t.u64().name("lobby_id"),
  status: __t.string(),
  startedAt: __t.timestamp().name("started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
  dayPhase: __t.string().name("day_phase"),
  cycleNumber: __t.u64().name("cycle_number"),
  phaseStartedAt: __t.timestamp().name("phase_started_at"),
  fogActive: __t.bool().name("fog_active"),
  mapSeed: __t.u64().name("map_seed"),
});
