// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  totalGames: __t.u64().name("total_games"),
  totalSurvivalSecs: __t.u64().name("total_survival_secs"),
  bestSurvivalSecs: __t.u64().name("best_survival_secs"),
  classSpotter: __t.u64().name("class_spotter"),
  classGunner: __t.u64().name("class_gunner"),
  classTank: __t.u64().name("class_tank"),
  classHealer: __t.u64().name("class_healer"),
});
