// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  playerIdentity: __t.identity().name("player_identity"),
  healCooldownUntil: __t.option(__t.timestamp()).name("heal_cooldown_until"),
  reviveCooldownUntil: __t.option(__t.timestamp()).name("revive_cooldown_until"),
  lastHealAt: __t.option(__t.timestamp()).name("last_heal_at"),
  healTargetIdentity: __t.option(__t.identity()).name("heal_target_identity"),
  chainHealTargetIdentity: __t.option(__t.identity()).name("chain_heal_target_identity"),
  ultimateCooldownUntil: __t.option(__t.timestamp()).name("ultimate_cooldown_until"),
  lastUltimateAt: __t.option(__t.timestamp()).name("last_ultimate_at"),
  regenCarry: __t.u64().name("regen_carry"),
});
