// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  hostIdentity: __t.identity().name("host_identity"),
  code: __t.string(),
  isPublic: __t.bool().name("is_public"),
  status: __t.string(),
  playerCount: __t.u64().name("player_count"),
  maxPlayers: __t.u64().name("max_players"),
  createdAt: __t.timestamp().name("created_at"),
  hostIdleDeadline: __t.timestamp().name("host_idle_deadline"),
});
