// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  sourceIdentity: __t.identity().name("source_identity"),
  targetType: __t.string().name("target_type"),
  posX: __t.i64().name("pos_x"),
  posZ: __t.i64().name("pos_z"),
  expiresAt: __t.timestamp().name("expires_at"),
});
