// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  playerIdentity: __t.identity().name("player_identity"),
  classChoice: __t.string().name("class_choice"),
  hp: __t.u64(),
  maxHp: __t.u64().name("max_hp"),
  stamina: __t.u64(),
  maxStamina: __t.u64().name("max_stamina"),
  lastMoveAt: __t.timestamp().name("last_move_at"),
  staminaRegenStartAt: __t.option(__t.timestamp()).name("stamina_regen_start_at"),
  staminaRegenCarry: __t.u64().name("stamina_regen_carry"),
  lastShotAt: __t.option(__t.timestamp()).name("last_shot_at"),
  posX: __t.i64().name("pos_x"),
  posY: __t.i64().name("pos_y"),
  posZ: __t.i64().name("pos_z"),
  status: __t.string(),
  score: __t.u64(),
  facingAngle: __t.i64().name("facing_angle"),
  speedBoostUntil: __t.option(__t.timestamp()).name("speed_boost_until"),
  doubleDamageUntil: __t.option(__t.timestamp()).name("double_damage_until"),
  stunUntil: __t.option(__t.timestamp()).name("stun_until"),
  slowedUntil: __t.option(__t.timestamp()).name("slowed_until"),
  lastDamagedAt: __t.option(__t.timestamp()).name("last_damaged_at"),
});
