// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  playerIdentity: __t.identity().name("player_identity"),
  classChoice: __t.string().name("class_choice"),
  hp: __t.u64(),
  maxHp: __t.u64().name("max_hp"),
  stamina: __t.u64(),
  maxStamina: __t.u64().name("max_stamina"),
  posX: __t.i64().name("pos_x"),
  posY: __t.i64().name("pos_y"),
  posZ: __t.i64().name("pos_z"),
  status: __t.string(),
  score: __t.u64(),
});
