// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  playerIdentity: __t.identity().name("player_identity"),
  steadyShotCooldownUntil: __t.option(__t.timestamp()).name("steady_shot_cooldown_until"),
  flashCooldownUntil: __t.option(__t.timestamp()).name("flash_cooldown_until"),
  lastFlashAt: __t.option(__t.timestamp()).name("last_flash_at"),
  ultimateCooldownUntil: __t.option(__t.timestamp()).name("ultimate_cooldown_until"),
  lastUltimateAt: __t.option(__t.timestamp()).name("last_ultimate_at"),
});
