// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  playerIdentity: __t.identity().name("player_identity"),
  isCharging: __t.bool().name("is_charging"),
  chargeUntil: __t.option(__t.timestamp()).name("charge_until"),
  chargeDirX: __t.i64().name("charge_dir_x"),
  chargeDirZ: __t.i64().name("charge_dir_z"),
  chargeCooldownUntil: __t.option(__t.timestamp()).name("charge_cooldown_until"),
  axeSwingCooldownUntil: __t.option(__t.timestamp()).name("axe_swing_cooldown_until"),
  lastAxeSwingAt: __t.option(__t.timestamp()).name("last_axe_swing_at"),
  lastChargeAt: __t.option(__t.timestamp()).name("last_charge_at"),
  ultimateCooldownUntil: __t.option(__t.timestamp()).name("ultimate_cooldown_until"),
  lastUltimateAt: __t.option(__t.timestamp()).name("last_ultimate_at"),
});
