// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AcidPool = __t.object("AcidPool", {
  id: __t.u64(),
  sessionId: __t.u64(),
  posX: __t.i64(),
  posZ: __t.i64(),
  radius: __t.u64(),
  expiresAt: __t.timestamp(),
});
export type AcidPool = __Infer<typeof AcidPool>;

export const Boss = __t.object("Boss", {
  id: __t.u64(),
  sessionId: __t.u64(),
  bossType: __t.string(),
  hp: __t.u64(),
  maxHp: __t.u64(),
  posX: __t.i64(),
  posZ: __t.i64(),
  phase: __t.u64(),
  isAlive: __t.bool(),
  isDazed: __t.bool(),
  dazedUntil: __t.option(__t.timestamp()),
  isMarked: __t.bool(),
  markedUntil: __t.option(__t.timestamp()),
  spawnedAt: __t.timestamp(),
  diedAt: __t.option(__t.timestamp()),
  ability1CooldownUntil: __t.option(__t.timestamp()),
  ability2CooldownUntil: __t.option(__t.timestamp()),
  isHidden: __t.bool(),
  isBurrowed: __t.bool(),
  isChanneling: __t.bool(),
  knockedPlayerId: __t.option(__t.u64()),
});
export type Boss = __Infer<typeof Boss>;

export const BossSpawnJob = __t.object("BossSpawnJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  sessionId: __t.u64(),
});
export type BossSpawnJob = __Infer<typeof BossSpawnJob>;

export const BossTimer = __t.object("BossTimer", {
  id: __t.u64(),
  sessionId: __t.u64(),
  spawnAt: __t.timestamp(),
});
export type BossTimer = __Infer<typeof BossTimer>;

export const DayPhaseJob = __t.object("DayPhaseJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  sessionId: __t.u64(),
});
export type DayPhaseJob = __Infer<typeof DayPhaseJob>;

export const DroppedItem = __t.object("DroppedItem", {
  id: __t.u64(),
  sessionId: __t.u64(),
  itemType: __t.string(),
  posX: __t.i64(),
  posZ: __t.i64(),
  spawnedAt: __t.timestamp(),
});
export type DroppedItem = __Infer<typeof DroppedItem>;

export const Enemy = __t.object("Enemy", {
  id: __t.u64(),
  sessionId: __t.u64(),
  enemyType: __t.string(),
  hp: __t.u64(),
  maxHp: __t.u64(),
  posX: __t.i64(),
  posZ: __t.i64(),
  speedMultiplier: __t.u64(),
  isDazed: __t.bool(),
  dazedUntil: __t.option(__t.timestamp()),
  isAlive: __t.bool(),
  isMarked: __t.bool(),
  markedUntil: __t.option(__t.timestamp()),
  lastSpitAt: __t.option(__t.timestamp()),
  diedAt: __t.option(__t.timestamp()),
  spawnedAt: __t.option(__t.timestamp()),
});
export type Enemy = __Infer<typeof Enemy>;

export const EnemySpawnJob = __t.object("EnemySpawnJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  sessionId: __t.u64(),
});
export type EnemySpawnJob = __Infer<typeof EnemySpawnJob>;

export const EnemyTickJob = __t.object("EnemyTickJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  sessionId: __t.u64(),
});
export type EnemyTickJob = __Infer<typeof EnemyTickJob>;

export const GameSession = __t.object("GameSession", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  status: __t.string(),
  startedAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  dayPhase: __t.string(),
  cycleNumber: __t.u64(),
  phaseStartedAt: __t.timestamp(),
  fogStartedAt: __t.option(__t.timestamp()),
  fogEndsAt: __t.option(__t.timestamp()),
  mapSeed: __t.u64(),
  bossSpawnCount: __t.u64(),
});
export type GameSession = __Infer<typeof GameSession>;

export const GlobalStats = __t.object("GlobalStats", {
  id: __t.u64(),
  totalGames: __t.u64(),
  totalSurvivalSecs: __t.u64(),
  bestSurvivalSecs: __t.u64(),
  classSpotter: __t.u64(),
  classGunner: __t.u64(),
  classTank: __t.u64(),
  classHealer: __t.u64(),
});
export type GlobalStats = __Infer<typeof GlobalStats>;

export const GunnerState = __t.object("GunnerState", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerIdentity: __t.identity(),
  adrenalineCooldownUntil: __t.option(__t.timestamp()),
  lastAdrenalineAt: __t.option(__t.timestamp()),
  ultimateCooldownUntil: __t.option(__t.timestamp()),
  lastUltimateAt: __t.option(__t.timestamp()),
});
export type GunnerState = __Infer<typeof GunnerState>;

export const HealerState = __t.object("HealerState", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerIdentity: __t.identity(),
  healCooldownUntil: __t.option(__t.timestamp()),
  reviveCooldownUntil: __t.option(__t.timestamp()),
  lastHealAt: __t.option(__t.timestamp()),
  healTargetIdentity: __t.option(__t.identity()),
  chainHealTargetIdentity: __t.option(__t.identity()),
  ultimateCooldownUntil: __t.option(__t.timestamp()),
  lastUltimateAt: __t.option(__t.timestamp()),
  regenCarry: __t.u64(),
});
export type HealerState = __Infer<typeof HealerState>;

export const Lobby = __t.object("Lobby", {
  id: __t.u64(),
  hostIdentity: __t.identity(),
  code: __t.string(),
  isPublic: __t.bool(),
  status: __t.string(),
  playerCount: __t.u64(),
  maxPlayers: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Lobby = __Infer<typeof Lobby>;

export const LobbyAfkJob = __t.object("LobbyAfkJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  lobbyId: __t.u64(),
  playerIdentity: __t.identity(),
});
export type LobbyAfkJob = __Infer<typeof LobbyAfkJob>;

export const LobbyCountdown = __t.object("LobbyCountdown", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  lobbyId: __t.u64(),
});
export type LobbyCountdown = __Infer<typeof LobbyCountdown>;

export const LobbyMessage = __t.object("LobbyMessage", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  playerIdentity: __t.identity(),
  playerName: __t.string(),
  message: __t.string(),
  sentAt: __t.timestamp(),
});
export type LobbyMessage = __Infer<typeof LobbyMessage>;

export const LobbyPlayer = __t.object("LobbyPlayer", {
  id: __t.u64(),
  lobbyId: __t.u64(),
  playerIdentity: __t.identity(),
  playerName: __t.string(),
  classChoice: __t.string(),
  isReady: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type LobbyPlayer = __Infer<typeof LobbyPlayer>;

export const LobbyResult = __t.object("LobbyResult", {
  id: __t.u64(),
  sessionId: __t.u64(),
  lobbyCode: __t.string(),
  combo: __t.string(),
  playerCount: __t.u64(),
  totalScore: __t.u64(),
  survivalSecs: __t.u64(),
  cycleNumber: __t.u64(),
  createdAt: __t.timestamp(),
});
export type LobbyResult = __Infer<typeof LobbyResult>;

export const LobbyResultPlayer = __t.object("LobbyResultPlayer", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerName: __t.string(),
  classChoice: __t.string(),
});
export type LobbyResultPlayer = __Infer<typeof LobbyResultPlayer>;

export const Mark = __t.object("Mark", {
  id: __t.u64(),
  sessionId: __t.u64(),
  sourceIdentity: __t.identity(),
  targetType: __t.string(),
  posX: __t.i64(),
  posZ: __t.i64(),
  expiresAt: __t.timestamp(),
});
export type Mark = __Infer<typeof Mark>;

export const PlayerState = __t.object("PlayerState", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerIdentity: __t.identity(),
  classChoice: __t.string(),
  hp: __t.u64(),
  maxHp: __t.u64(),
  stamina: __t.u64(),
  maxStamina: __t.u64(),
  lastMoveAt: __t.timestamp(),
  staminaRegenStartAt: __t.option(__t.timestamp()),
  staminaRegenCarry: __t.u64(),
  lastShotAt: __t.option(__t.timestamp()),
  posX: __t.i64(),
  posY: __t.i64(),
  posZ: __t.i64(),
  status: __t.string(),
  score: __t.u64(),
  facingAngle: __t.i64(),
  speedBoostUntil: __t.option(__t.timestamp()),
  doubleDamageUntil: __t.option(__t.timestamp()),
  stunUntil: __t.option(__t.timestamp()),
  slowedUntil: __t.option(__t.timestamp()),
  lastDamagedAt: __t.option(__t.timestamp()),
});
export type PlayerState = __Infer<typeof PlayerState>;

export const ReviveChannel = __t.object("ReviveChannel", {
  id: __t.u64(),
  sessionId: __t.u64(),
  healerIdentity: __t.identity(),
  targetIdentity: __t.identity(),
  channelStartedAt: __t.timestamp(),
  shieldHp: __t.u64(),
});
export type ReviveChannel = __Infer<typeof ReviveChannel>;

export const ReviveCompleteJob = __t.object("ReviveCompleteJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  sessionId: __t.u64(),
  healerIdentity: __t.identity(),
  targetIdentity: __t.identity(),
});
export type ReviveCompleteJob = __Infer<typeof ReviveCompleteJob>;

export const SpotterState = __t.object("SpotterState", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerIdentity: __t.identity(),
  steadyShotCooldownUntil: __t.option(__t.timestamp()),
  flashCooldownUntil: __t.option(__t.timestamp()),
  lastFlashAt: __t.option(__t.timestamp()),
  ultimateCooldownUntil: __t.option(__t.timestamp()),
  lastUltimateAt: __t.option(__t.timestamp()),
});
export type SpotterState = __Infer<typeof SpotterState>;

export const SquadRecord = __t.object("SquadRecord", {
  id: __t.u64(),
  combo: __t.string(),
  timesPlayed: __t.u64(),
  bestScore: __t.u64(),
  bestSurvivalSecs: __t.u64(),
});
export type SquadRecord = __Infer<typeof SquadRecord>;

export const TankState = __t.object("TankState", {
  id: __t.u64(),
  sessionId: __t.u64(),
  playerIdentity: __t.identity(),
  isCharging: __t.bool(),
  chargeUntil: __t.option(__t.timestamp()),
  chargeDirX: __t.i64(),
  chargeDirZ: __t.i64(),
  chargeCooldownUntil: __t.option(__t.timestamp()),
  axeSwingCooldownUntil: __t.option(__t.timestamp()),
  lastAxeSwingAt: __t.option(__t.timestamp()),
  lastChargeAt: __t.option(__t.timestamp()),
  ultimateCooldownUntil: __t.option(__t.timestamp()),
  lastUltimateAt: __t.option(__t.timestamp()),
});
export type TankState = __Infer<typeof TankState>;

