// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateLobbyReducer from "../create_lobby_reducer";
import JoinByCodeReducer from "../join_by_code_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import LeaveLobbyReducer from "../leave_lobby_reducer";
import MovePlayerReducer from "../move_player_reducer";
import SetClassReducer from "../set_class_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartCountdownReducer from "../start_countdown_reducer";

export type CreateLobbyParams = __Infer<typeof CreateLobbyReducer>;
export type JoinByCodeParams = __Infer<typeof JoinByCodeReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type LeaveLobbyParams = __Infer<typeof LeaveLobbyReducer>;
export type MovePlayerParams = __Infer<typeof MovePlayerReducer>;
export type SetClassParams = __Infer<typeof SetClassReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartCountdownParams = __Infer<typeof StartCountdownReducer>;

